name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      # Install dependencies for api-gateway
      - name: Install dependencies for api-gateway
        run: yarn install --cwd ./api-gateway

      - name: Build api-gateway
        run: yarn build --cwd ./api-gateway

      # Install dependencies for user-service
      - name: Install dependencies for user-service
        run: yarn install --cwd ./user-service

      - name: Build user-service
        run: yarn build --cwd ./user-service

      # Install dependencies for notification-service
      - name: Install dependencies for notification-service
        run: yarn install --cwd ./notification-service

      - name: Build notification-service
        run: yarn build --cwd ./notification-service

      # Install dependencies for product-service
      - name: Install dependencies for product-service
        run: yarn install --cwd ./product-service

      - name: Build product-service
        run: yarn build --cwd ./product-service

      # Install dependencies for cart-service
      - name: Install dependencies for cart-service
        run: yarn install --cwd ./cart-service

      - name: Build cart-service
        run: yarn build --cwd ./cart-service




#         For testing only
#       - name: Run tests for notification-service
#         run: yarn test --cwd ./notification-service