name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        env:
          ALLOW_ANONYMOUS_LOGIN: yes

      kafka:
        image: 'bitnami/kafka:latest'
        ports:
          - '9092:9092'
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
        options: >-
          --user root
          --volume ./Kafka:/bitnami/kafka
        depends_on:
          - zookeeper

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      # Install, test, and build for each service
      - name: Install dependencies for api-gateway
        run: yarn install --cwd ./api-gateway

      - name: Run tests for api-gateway
        run: yarn test --cwd ./api-gateway

      - name: Build api-gateway
        run: yarn build --cwd ./api-gateway

      - name: Install dependencies for user-service
        run: yarn install --cwd ./user-service

      - name: Run tests for user-service
        run: yarn test --cwd ./user-service

      - name: Build user-service
        run: yarn build --cwd ./user-service

      - name: Install dependencies for notification-service
        run: yarn install --cwd ./notification-service

      - name: Run tests for notification-service
        run: yarn test --cwd ./notification-service

      - name: Build notification-service
        run: yarn build --cwd ./notification-service

      - name: Install dependencies for product-service
        run: yarn install --cwd ./product-service

      - name: Run tests for product-service
        run: yarn test --cwd ./product-service

      - name: Build product-service
        run: yarn build --cwd ./product-service

      - name: Install dependencies for cart-service
        run: yarn install --cwd ./cart-service

      - name: Run tests for cart-service
        run: yarn test --cwd ./cart-service

      - name: Build cart-service
        run: yarn build --cwd ./cart-service
