name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    # Install, build for each service
    - name: Install dependencies and build user-service
      run: |
        cd user-service
        yarn install --frozen-lockfile
        yarn build

    - name: Install dependencies and build notification-service
      run: |
        cd notification-service
        yarn install --frozen-lockfile
        yarn build

    - name: Install dependencies and build product-service
      run: |
        cd product-service
        yarn install --frozen-lockfile
        yarn build

    - name: Install dependencies and build cart-service
      run: |
        cd cart-service
        yarn install --frozen-lockfile
        yarn build

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   # Build and push Docker images for each service
  #   - name: Build and push user-service
  #     run: |
  #       docker build -t your-dockerhub-username/user-service:latest ./user-service
  #       docker push your-dockerhub-username/user-service:latest

  #   - name: Build and push notification-service
  #     run: |
  #       docker build -t your-dockerhub-username/notification-service:latest ./notification-service
  #       docker push your-dockerhub-username/notification-service:latest

  #   - name: Build and push product-service
  #     run: |
  #       docker build -t your-dockerhub-username/product-service:latest ./product-service
  #       docker push your-dockerhub-username/product-service:latest

  #   - name: Build and push cart-service
  #     run: |
  #       docker build -t your-dockerhub-username/cart-service:latest ./cart-service
  #       docker push your-dockerhub-username/cart-service:latest
  #for testing purpose 
  # - name: Run tests for cart-service
      #   run: yarn test --cwd ./cart-service
